version: '3.9'

services:
    nginx:
        image: nginx:stable-alpine
        # container_name: nginx-test
        # build: 
        #     context: ./
        #     dockerfile: Dockerfile
        restart: always
        ports: 
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./cert/:/etc/nginx/ssl:delegated
        depends_on:
            - wordpress-1
            - wordpress-2
        networks:
            - wpsite

    wordpress-1:
        build: 
            context: ./wordpress
            dockerfile: Dockerfile
        container_name: wordpress-test-1
        ports:
            - '8000:80'
        restart: always
        volumes: 
            - ./:/var/www/html:delegated
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        depends_on:
            - mysql 
        networks:
            - wpsite
    
    wordpress-2:
        build: 
            context: ./wordpress
            dockerfile: Dockerfile
        container_name: wordpress-test-2
        ports:
            - '8080:80'
        restart: always
        volumes: 
            - ./:/var/www/html:delegated
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        depends_on:
            - mysql
            - wordpress-1
        networks:
            - wpsite        

    mysql:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - wpsite

networks:
    wpsite:
        driver: bridge
volumes:
  db_data: